### PR TITLE
Bumping fabric8 k8s client to 6.7.2 and adjusting OpenShift class accordingly

### PR DESCRIPTION
**Pull request by fabiobrz**
Hi @RoyalKarma - a draft for a potential solution about [what we discussed yesterday](https://github.com/xtf-cz/xtf/pull/532#discussion_r1269702354).
This is just a first stab, and I am going to play/test a little bit more with it, since I havent tried at all it yet.
I'll keep you posted.
 
Please make sure your PR meets the following requirements:
- [ ] Pull Request contains a description of the changes
- [ ] Pull Request does not include fixes for multiple issues/topics
- [ ] Code is formatted, imports ordered, code compiles and tests are passing
- [ ] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by fabiobrz** [comment]
I improved it by using the Client adapter approach which is already designed and used in the kubernetes client, see  https://github.com/fabric8io/kubernetes-client/blob/v6.7.2/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ClientAdapter.java and https://github.com/fabric8io/kubernetes-client/blob/v6.7.2/openshift-client-api/src/main/java/io/fabric8/openshift/client/NamespacedOpenShiftClientAdapter.java

`mvn clean install` is now green including local XTF tests.

Next step I'll run some integration tests from Intersmash.

**Comment by RoyalKarma** [comment]
Hi, thank you, I've played around with your changes, tests are still mostly failing with
```
Failure executing: GET at: . Message: pods is forbidden: User "" cannot list resource "pods" in API group "" in the namespace "8". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods is forbidden: User "" cannot list resource "pods" in API group "" in the namespace "80-openjdk17-o7m4", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
```
Last time I had this issue, it was caused by missing ```.admin()``` in a test, but I'm not sure why its an issue now. When I run the tests locally with the admin token set, they pass fine so I think this is the correct solution.
Also version 6.8.0 of the client released, but it doesnt seem to break anything this time.

**Comment by fabiobrz** [comment]
> Hi, thank you, I've played around with your changes, tests are still mostly failing with
> 
> ```
> Failure executing: GET at: . Message: pods is forbidden: User "" cannot list resource "pods" in API group "" in the namespace "8". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods is forbidden: User "" cannot list resource "pods" in API group "" in the namespace "80-openjdk17-o7m4", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
> ```
I don't know what this issue is about. From the details it looks to me as you're testing the changes through the EAP QE OpenShift TS. I am doing the same with Intersmash, and [it seems to work](https://github.com/Intersmash/intersmash/pull/69) (except for some failures I still need to fix) . Have you tried [referencing the XTF SNAPSHOT](https://github.com/Intersmash/intersmash/pull/69/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R31) based on our cumulative changes that I released a couple of days ago?

**Comment by RoyalKarma** [comment]
Yes, I'm using the new snapshot, but still no luck with the errors. I don't see anything in the client changelog that could be causing this.

**Comment by simkam** [comment]
I sent an upgrade to 6.8.1 to @fabiobrz 's branch. It includes the fix that was causing problems in OpenShift TS - commented-out token matching. @RoyalKarma When merged please run full tests again. 

https://github.com/fabiobrz/xtf/pull/1

**Pull request merged**
